name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Test suite setup
        uses: fluxcd/gha-workflows/.github/actions/setup-kubernetes@v0.10.0
        with:
          go-version: 1.26.x
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@1fd61a06264d71cf445ed55c4f14d401d26a1c64 # v2.8.8
      - name: Run tests
        run: make test
      - name: Run linters
        run: make lint
      - name: Build binary
        run: make build
      - name: Run smoke test
        run: |
          flux install --export | ./bin/flux-schema validate -v --schema-location ./catalog/latest
      - name: Build Docker image
        run: make docker-build
      - name: Run Docker smoke test
        run: |
          flux install --export | docker run --rm -i ghcr.io/fluxcd/flux-schema:latest-dev \
            validate -v --schema-location /catalog/latest
      - name: Check if working tree is dirty
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            git --no-pager diff
            echo 'run make test and commit changes'
            exit 1
          fi
